### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tech-apollofinvest** [aws-solutions/aws-instance-scheduler#305]
$ scheduler-cli create-period --stack Ec2instanceScheduler --region ap-south-1 --name mon-fri-8-8 --begintime 8:00 --endtime 7:59 --weekdays mon-fri
Traceback (most recent call last):
  File "/usr/bin/scheduler-cli", line 11, in <module>
    load_entry_point('scheduler-cli==1.4.0', 'console_scripts', 'scheduler-cli')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/scheduler_cli/scheduler_cli.py", line 18, in <module>
  File "/usr/lib/python2.7/site-packages/boto3-1.21.15-py2.7.egg/boto3/__init__.py", line 16, in <module>
    from boto3.compat import _warn_deprecated_python
  File "/usr/lib/python2.7/site-packages/boto3-1.21.15-py2.7.egg/boto3/compat.py", line 20, in <module>
    from boto3.exceptions import PythonDeprecationWarning
  File "/usr/lib/python2.7/site-packages/boto3-1.21.15-py2.7.egg/boto3/exceptions.py", line 43
    f"The '{service_name}' resource does not an API version of: {bad_api_version}\n"
                                                                                   ^

Even though I have activated the python3 environment, scheduler CLI is using 2.7.

**Comment by Robertndrei** [comment]
I'm getting the same error.

**Comment by praveenis** [comment]
Hi @tech-apollofinvest / @Robertndrei 

We are not able to reproduce this issue from our end.  As I did the below steps

1.Downloaded the scheduler-cli from this location https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/scheduler-cli.zip.
2. Unzip it and Install the schedulure-cli setup using Python3

Thanks,
Praveen

**Comment by Darthstevo** [comment]
@praveenis 

The documentation doesnt say anything about using python3 now:
https://docs.aws.amazon.com/solutions/latest/instance-scheduler/scheduler-cli.html#install

That should probably be updated, I don't think the scheduler-cli was supported on python3 till recently.

**Comment by macdrorepo** [comment]
This is still not corrected, scheduler is installing with python2.x by default
